# Generated by Django 5.1.7 on 2025-03-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='duty_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='exam_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=50)),
                ('center_incharge', models.CharField(max_length=50)),
                ('gtu_co', models.CharField(max_length=50)),
                ('sr_sup', models.CharField(max_length=50)),
                ('jr_sup', models.CharField(max_length=50)),
                ('st_sup', models.CharField(max_length=50)),
                ('num_sup', models.CharField(max_length=50)),
                ('peon', models.CharField(max_length=50)),
                ('st_peon', models.CharField(max_length=50)),
                ('sweeper', models.CharField(max_length=50)),
                ('page_amount', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
    ]
