# Generated by Django 5.1.4 on 2025-04-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='duty_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='exam_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=50, unique=True)),
                ('center_incharge', models.IntegerField()),
                ('gtu_co', models.IntegerField()),
                ('sr_sup', models.IntegerField()),
                ('jr_sup', models.IntegerField()),
                ('st_sup', models.IntegerField()),
                ('num_sup', models.IntegerField()),
                ('peon', models.IntegerField()),
                ('st_peon', models.IntegerField()),
                ('sweeper', models.IntegerField()),
                ('page_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.department')),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.session')),
            ],
        ),
    ]
