# Generated by Django 5.1.7 on 2025-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_name',
            name='center_incharge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='gtu_co',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='jr_sup',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='num_sup',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='page_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='peon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='sr_sup',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='st_peon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='st_sup',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam_name',
            name='sweeper',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pancard',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
