# Generated by Django 5.1.7 on 2025-04-01 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_exam_name_center_incharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.department'),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.session'),
        ),
    ]
