# Generated by Django 5.1.7 on 2025-04-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_faculty_department_alter_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.session'),
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
