# Generated by Django 5.1.7 on 2025-04-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_time_session_id_alter_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_name',
            name='exam',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
