# Generated by Django 5.1.4 on 2025-04-06 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gtu_th_exam_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('block', models.PositiveIntegerField(default=0)),
                ('duty_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.duty_type')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.exam_name')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.semester')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.session')),
                ('time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.time')),
            ],
        ),
    ]
