# Generated by Django 5.1.7 on 2025-04-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTUEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtu_th_exam_data',
            name='block',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
