# Generated by Django 5.1.7 on 2025-04-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTUEntry', '0004_gtu_th_cp_data_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub10_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub10_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub11_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub11_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub12_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub12_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub1_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub1_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub2_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub2_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub3_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub3_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub4_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub4_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub5_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub5_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub6_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub6_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub7_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub7_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub8_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub8_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub9_no_of_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='sub9_no_of_student',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gtu_th_cp_data',
            name='total_pages',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
