# Generated by Django 5.1.7 on 2025-03-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gtu_cordinator', 'GTU Coordinator'), ('department', 'Department')], max_length=50),
        ),
    ]
