# Generated by Django 5.1.7 on 2025-03-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_custumuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
