# Generated by Django 5.1.7 on 2025-03-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_custumuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('gtu_cordinator', 'gtu_cordinator'), ('department', 'department')], max_length=50),
        ),
    ]
