# Generated by Django 5.1.7 on 2025-03-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_custumuser_role'),
        ('authenticate', '0004_alter_custumuser_role'),
    ]

    operations = [
    ]
